// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gpencil/upload/internal/dal/model"
)

func newScenarios(db *gorm.DB, opts ...gen.DOOption) scenarios {
	_scenarios := scenarios{}

	_scenarios.scenariosDo.UseDB(db, opts...)
	_scenarios.scenariosDo.UseModel(&model.Scenarios{})

	tableName := _scenarios.scenariosDo.TableName()
	_scenarios.ALL = field.NewAsterisk(tableName)
	_scenarios.ID = field.NewInt64(tableName, "id")
	_scenarios.Name = field.NewString(tableName, "name")
	_scenarios.Description = field.NewString(tableName, "description")
	_scenarios.ImageURL = field.NewString(tableName, "image_url")
	_scenarios.Status = field.NewBool(tableName, "status")
	_scenarios.CreatedAt = field.NewInt64(tableName, "created_at")
	_scenarios.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_scenarios.fillFieldMap()

	return _scenarios
}

// scenarios 场景配置表
type scenarios struct {
	scenariosDo scenariosDo

	ALL         field.Asterisk
	ID          field.Int64  // 场景ID - 使用Snowflake算法生成
	Name        field.String // 场景名称
	Description field.String // 场景描述
	ImageURL    field.String // 场景图片URL
	Status      field.Bool   // 状态：1=启用，0=禁用
	CreatedAt   field.Int64  // 创建时间
	UpdatedAt   field.Int64  // 更新时间

	fieldMap map[string]field.Expr
}

func (s scenarios) Table(newTableName string) *scenarios {
	s.scenariosDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s scenarios) As(alias string) *scenarios {
	s.scenariosDo.DO = *(s.scenariosDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *scenarios) updateTableName(table string) *scenarios {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.Description = field.NewString(table, "description")
	s.ImageURL = field.NewString(table, "image_url")
	s.Status = field.NewBool(table, "status")
	s.CreatedAt = field.NewInt64(table, "created_at")
	s.UpdatedAt = field.NewInt64(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *scenarios) WithContext(ctx context.Context) *scenariosDo {
	return s.scenariosDo.WithContext(ctx)
}

func (s scenarios) TableName() string { return s.scenariosDo.TableName() }

func (s scenarios) Alias() string { return s.scenariosDo.Alias() }

func (s scenarios) Columns(cols ...field.Expr) gen.Columns { return s.scenariosDo.Columns(cols...) }

func (s *scenarios) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *scenarios) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["description"] = s.Description
	s.fieldMap["image_url"] = s.ImageURL
	s.fieldMap["status"] = s.Status
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s scenarios) clone(db *gorm.DB) scenarios {
	s.scenariosDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s scenarios) replaceDB(db *gorm.DB) scenarios {
	s.scenariosDo.ReplaceDB(db)
	return s
}

type scenariosDo struct{ gen.DO }

func (s scenariosDo) Debug() *scenariosDo {
	return s.withDO(s.DO.Debug())
}

func (s scenariosDo) WithContext(ctx context.Context) *scenariosDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s scenariosDo) ReadDB() *scenariosDo {
	return s.Clauses(dbresolver.Read)
}

func (s scenariosDo) WriteDB() *scenariosDo {
	return s.Clauses(dbresolver.Write)
}

func (s scenariosDo) Session(config *gorm.Session) *scenariosDo {
	return s.withDO(s.DO.Session(config))
}

func (s scenariosDo) Clauses(conds ...clause.Expression) *scenariosDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s scenariosDo) Returning(value interface{}, columns ...string) *scenariosDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s scenariosDo) Not(conds ...gen.Condition) *scenariosDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s scenariosDo) Or(conds ...gen.Condition) *scenariosDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s scenariosDo) Select(conds ...field.Expr) *scenariosDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s scenariosDo) Where(conds ...gen.Condition) *scenariosDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s scenariosDo) Order(conds ...field.Expr) *scenariosDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s scenariosDo) Distinct(cols ...field.Expr) *scenariosDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s scenariosDo) Omit(cols ...field.Expr) *scenariosDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s scenariosDo) Join(table schema.Tabler, on ...field.Expr) *scenariosDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s scenariosDo) LeftJoin(table schema.Tabler, on ...field.Expr) *scenariosDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s scenariosDo) RightJoin(table schema.Tabler, on ...field.Expr) *scenariosDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s scenariosDo) Group(cols ...field.Expr) *scenariosDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s scenariosDo) Having(conds ...gen.Condition) *scenariosDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s scenariosDo) Limit(limit int) *scenariosDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s scenariosDo) Offset(offset int) *scenariosDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s scenariosDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *scenariosDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s scenariosDo) Unscoped() *scenariosDo {
	return s.withDO(s.DO.Unscoped())
}

func (s scenariosDo) Create(values ...*model.Scenarios) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s scenariosDo) CreateInBatches(values []*model.Scenarios, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s scenariosDo) Save(values ...*model.Scenarios) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s scenariosDo) First() (*model.Scenarios, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Scenarios), nil
	}
}

func (s scenariosDo) Take() (*model.Scenarios, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Scenarios), nil
	}
}

func (s scenariosDo) Last() (*model.Scenarios, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Scenarios), nil
	}
}

func (s scenariosDo) Find() ([]*model.Scenarios, error) {
	result, err := s.DO.Find()
	return result.([]*model.Scenarios), err
}

func (s scenariosDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Scenarios, err error) {
	buf := make([]*model.Scenarios, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s scenariosDo) FindInBatches(result *[]*model.Scenarios, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s scenariosDo) Attrs(attrs ...field.AssignExpr) *scenariosDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s scenariosDo) Assign(attrs ...field.AssignExpr) *scenariosDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s scenariosDo) Joins(fields ...field.RelationField) *scenariosDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s scenariosDo) Preload(fields ...field.RelationField) *scenariosDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s scenariosDo) FirstOrInit() (*model.Scenarios, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Scenarios), nil
	}
}

func (s scenariosDo) FirstOrCreate() (*model.Scenarios, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Scenarios), nil
	}
}

func (s scenariosDo) FindByPage(offset int, limit int) (result []*model.Scenarios, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s scenariosDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s scenariosDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s scenariosDo) Delete(models ...*model.Scenarios) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *scenariosDo) withDO(do gen.Dao) *scenariosDo {
	s.DO = *do.(*gen.DO)
	return s
}
