// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gpencil/upload/internal/dal/model"
)

func newVoices(db *gorm.DB, opts ...gen.DOOption) voices {
	_voices := voices{}

	_voices.voicesDo.UseDB(db, opts...)
	_voices.voicesDo.UseModel(&model.Voices{})

	tableName := _voices.voicesDo.TableName()
	_voices.ALL = field.NewAsterisk(tableName)
	_voices.ID = field.NewInt64(tableName, "id")
	_voices.VoiceID = field.NewString(tableName, "voice_id")
	_voices.ScenarioID = field.NewInt64(tableName, "scenario_id")
	_voices.Name = field.NewString(tableName, "name")
	_voices.IconURL = field.NewString(tableName, "icon_url")
	_voices.Description = field.NewString(tableName, "description")
	_voices.PreviewURL = field.NewString(tableName, "preview_url")
	_voices.Gender = field.NewString(tableName, "gender")
	_voices.AgeGroup = field.NewString(tableName, "age_group")
	_voices.Style = field.NewString(tableName, "style")
	_voices.Language = field.NewString(tableName, "language")
	_voices.SortOrder = field.NewInt32(tableName, "sort_order")
	_voices.Status = field.NewBool(tableName, "status")
	_voices.CreatedAt = field.NewInt64(tableName, "created_at")
	_voices.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_voices.VoiceHash = field.NewString(tableName, "voice_hash")

	_voices.fillFieldMap()

	return _voices
}

// voices 声线配置表
type voices struct {
	voicesDo voicesDo

	ALL         field.Asterisk
	ID          field.Int64  // 属性ID - 使用Snowflake算法生成
	VoiceID     field.String // 声线ID（唯一标识）
	ScenarioID  field.Int64  // 场景ID - 使用Snowflake算法生成
	Name        field.String // 声线名称
	IconURL     field.String // 声线图标URL
	Description field.String // 声线描述
	PreviewURL  field.String // 试听地址URL
	Gender      field.String // 性别：male=男性，female=女性，neutral=中性
	AgeGroup    field.String // 年龄组：child=儿童，young=青年，adult=成年，elderly=老年
	Style       field.String // 声线风格（如：温柔、活泼、专业等）
	Language    field.String // 支持语言
	SortOrder   field.Int32  // 排序权重
	Status      field.Bool   // 状态：1=启用，0=禁用
	CreatedAt   field.Int64  // 创建时间
	UpdatedAt   field.Int64  // 更新时间
	VoiceHash   field.String // 音色hash值

	fieldMap map[string]field.Expr
}

func (v voices) Table(newTableName string) *voices {
	v.voicesDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v voices) As(alias string) *voices {
	v.voicesDo.DO = *(v.voicesDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *voices) updateTableName(table string) *voices {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.VoiceID = field.NewString(table, "voice_id")
	v.ScenarioID = field.NewInt64(table, "scenario_id")
	v.Name = field.NewString(table, "name")
	v.IconURL = field.NewString(table, "icon_url")
	v.Description = field.NewString(table, "description")
	v.PreviewURL = field.NewString(table, "preview_url")
	v.Gender = field.NewString(table, "gender")
	v.AgeGroup = field.NewString(table, "age_group")
	v.Style = field.NewString(table, "style")
	v.Language = field.NewString(table, "language")
	v.SortOrder = field.NewInt32(table, "sort_order")
	v.Status = field.NewBool(table, "status")
	v.CreatedAt = field.NewInt64(table, "created_at")
	v.UpdatedAt = field.NewInt64(table, "updated_at")
	v.VoiceHash = field.NewString(table, "voice_hash")

	v.fillFieldMap()

	return v
}

func (v *voices) WithContext(ctx context.Context) *voicesDo { return v.voicesDo.WithContext(ctx) }

func (v voices) TableName() string { return v.voicesDo.TableName() }

func (v voices) Alias() string { return v.voicesDo.Alias() }

func (v voices) Columns(cols ...field.Expr) gen.Columns { return v.voicesDo.Columns(cols...) }

func (v *voices) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *voices) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 16)
	v.fieldMap["id"] = v.ID
	v.fieldMap["voice_id"] = v.VoiceID
	v.fieldMap["scenario_id"] = v.ScenarioID
	v.fieldMap["name"] = v.Name
	v.fieldMap["icon_url"] = v.IconURL
	v.fieldMap["description"] = v.Description
	v.fieldMap["preview_url"] = v.PreviewURL
	v.fieldMap["gender"] = v.Gender
	v.fieldMap["age_group"] = v.AgeGroup
	v.fieldMap["style"] = v.Style
	v.fieldMap["language"] = v.Language
	v.fieldMap["sort_order"] = v.SortOrder
	v.fieldMap["status"] = v.Status
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
	v.fieldMap["voice_hash"] = v.VoiceHash
}

func (v voices) clone(db *gorm.DB) voices {
	v.voicesDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v voices) replaceDB(db *gorm.DB) voices {
	v.voicesDo.ReplaceDB(db)
	return v
}

type voicesDo struct{ gen.DO }

func (v voicesDo) Debug() *voicesDo {
	return v.withDO(v.DO.Debug())
}

func (v voicesDo) WithContext(ctx context.Context) *voicesDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v voicesDo) ReadDB() *voicesDo {
	return v.Clauses(dbresolver.Read)
}

func (v voicesDo) WriteDB() *voicesDo {
	return v.Clauses(dbresolver.Write)
}

func (v voicesDo) Session(config *gorm.Session) *voicesDo {
	return v.withDO(v.DO.Session(config))
}

func (v voicesDo) Clauses(conds ...clause.Expression) *voicesDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v voicesDo) Returning(value interface{}, columns ...string) *voicesDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v voicesDo) Not(conds ...gen.Condition) *voicesDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v voicesDo) Or(conds ...gen.Condition) *voicesDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v voicesDo) Select(conds ...field.Expr) *voicesDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v voicesDo) Where(conds ...gen.Condition) *voicesDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v voicesDo) Order(conds ...field.Expr) *voicesDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v voicesDo) Distinct(cols ...field.Expr) *voicesDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v voicesDo) Omit(cols ...field.Expr) *voicesDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v voicesDo) Join(table schema.Tabler, on ...field.Expr) *voicesDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v voicesDo) LeftJoin(table schema.Tabler, on ...field.Expr) *voicesDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v voicesDo) RightJoin(table schema.Tabler, on ...field.Expr) *voicesDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v voicesDo) Group(cols ...field.Expr) *voicesDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v voicesDo) Having(conds ...gen.Condition) *voicesDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v voicesDo) Limit(limit int) *voicesDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v voicesDo) Offset(offset int) *voicesDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v voicesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *voicesDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v voicesDo) Unscoped() *voicesDo {
	return v.withDO(v.DO.Unscoped())
}

func (v voicesDo) Create(values ...*model.Voices) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v voicesDo) CreateInBatches(values []*model.Voices, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v voicesDo) Save(values ...*model.Voices) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v voicesDo) First() (*model.Voices, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Voices), nil
	}
}

func (v voicesDo) Take() (*model.Voices, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Voices), nil
	}
}

func (v voicesDo) Last() (*model.Voices, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Voices), nil
	}
}

func (v voicesDo) Find() ([]*model.Voices, error) {
	result, err := v.DO.Find()
	return result.([]*model.Voices), err
}

func (v voicesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Voices, err error) {
	buf := make([]*model.Voices, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v voicesDo) FindInBatches(result *[]*model.Voices, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v voicesDo) Attrs(attrs ...field.AssignExpr) *voicesDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v voicesDo) Assign(attrs ...field.AssignExpr) *voicesDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v voicesDo) Joins(fields ...field.RelationField) *voicesDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v voicesDo) Preload(fields ...field.RelationField) *voicesDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v voicesDo) FirstOrInit() (*model.Voices, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Voices), nil
	}
}

func (v voicesDo) FirstOrCreate() (*model.Voices, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Voices), nil
	}
}

func (v voicesDo) FindByPage(offset int, limit int) (result []*model.Voices, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v voicesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v voicesDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v voicesDo) Delete(models ...*model.Voices) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *voicesDo) withDO(do gen.Dao) *voicesDo {
	v.DO = *do.(*gen.DO)
	return v
}
