// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	aliyun "github.com/gpencil/upload/internal/handler/aliyun"
	"github.com/gpencil/upload/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 静态文件服务
	server.AddRoutes(
		[]rest.Route{
			{
				Method: http.MethodGet,
				Path:   "/",
				Handler: func(w http.ResponseWriter, r *http.Request) {
					http.ServeFile(w, r, "static/upload.html")
				},
			},
		},
	)

	// 健康检查路由
	server.AddRoutes(
		[]rest.Route{
			{
				Method: http.MethodGet,
				Path:   "/healthz",
				Handler: func(w http.ResponseWriter, r *http.Request) {
					w.WriteHeader(http.StatusOK)
					w.Write([]byte(`{"status":"ok"}`))
				},
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取统一配置
				Method:  http.MethodGet,
				Path:    "/config",
				Handler: aliyun.GetUnifiedConfigHandler(serverCtx),
			},
			{
				// 查询列ID
				Method:  http.MethodGet,
				Path:    "/scenario_id",
				Handler: aliyun.ScenarioIdHandler(serverCtx),
			},
			{
				// 上传阿里云图片/音频
				Method:  http.MethodPost,
				Path:    "/upload/oss",
				Handler: aliyun.UploadOssHandler(serverCtx),
			},
			{
				// 上传/修改音线
				Method:  http.MethodPost,
				Path:    "/upload/voice",
				Handler: aliyun.UploadVoiceHandler(serverCtx),
			},
		},
	)
}
