// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameScenarios = "scenarios"

// Scenarios 场景配置表
type Scenarios struct {
	ID          int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:场景ID - 使用Snowflake算法生成" json:"id"` // 场景ID - 使用Snowflake算法生成
	Name        string  `gorm:"column:name;not null;comment:场景名称" json:"name"`                                    // 场景名称
	Description *string `gorm:"column:description;comment:场景描述" json:"description"`                               // 场景描述
	ImageURL    *string `gorm:"column:image_url;comment:场景图片URL" json:"image_url"`                                // 场景图片URL
	Status      *bool   `gorm:"column:status;default:1;comment:状态：1=启用，0=禁用" json:"status"`                       // 状态：1=启用，0=禁用
	CreatedAt   int64   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                        // 创建时间
	UpdatedAt   int64   `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                        // 更新时间
}

// TableName Scenarios's table name
func (*Scenarios) TableName() string {
	return TableNameScenarios
}
