// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVoices = "voices"

// Voices 声线配置表
type Voices struct {
	ID          int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:属性ID - 使用Snowflake算法生成" json:"id"`                  // 属性ID - 使用Snowflake算法生成
	VoiceID     string  `gorm:"column:voice_id;not null;comment:声线ID（唯一标识）" json:"voice_id"`                                       // 声线ID（唯一标识）
	ScenarioID  int64   `gorm:"column:scenario_id;not null;comment:场景ID - 使用Snowflake算法生成" json:"scenario_id"`                     // 场景ID - 使用Snowflake算法生成
	Name        string  `gorm:"column:name;not null;comment:声线名称" json:"name"`                                                     // 声线名称
	IconURL     *string `gorm:"column:icon_url;comment:声线图标URL" json:"icon_url"`                                                   // 声线图标URL
	Description *string `gorm:"column:description;comment:声线描述" json:"description"`                                                // 声线描述
	PreviewURL  *string `gorm:"column:preview_url;comment:试听地址URL" json:"preview_url"`                                             // 试听地址URL
	Gender      *string `gorm:"column:gender;default:neutral;comment:性别：male=男性，female=女性，neutral=中性" json:"gender"`               // 性别：male=男性，female=女性，neutral=中性
	AgeGroup    *string `gorm:"column:age_group;default:adult;comment:年龄组：child=儿童，young=青年，adult=成年，elderly=老年" json:"age_group"` // 年龄组：child=儿童，young=青年，adult=成年，elderly=老年
	Style       *string `gorm:"column:style;comment:声线风格（如：温柔、活泼、专业等）" json:"style"`                                               // 声线风格（如：温柔、活泼、专业等）
	Language    *string `gorm:"column:language;default:zh-CN;comment:支持语言" json:"language"`                                        // 支持语言
	SortOrder   *int32  `gorm:"column:sort_order;comment:排序权重" json:"sort_order"`                                                  // 排序权重
	Status      *bool   `gorm:"column:status;default:1;comment:状态：1=启用，0=禁用" json:"status"`                                        // 状态：1=启用，0=禁用
	CreatedAt   int64   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                                         // 创建时间
	UpdatedAt   int64   `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                                         // 更新时间
	VoiceHash   *string `gorm:"column:voice_hash;comment:音色hash值" json:"voice_hash"`                                               // 音色hash值
}

// TableName Voices's table name
func (*Voices) TableName() string {
	return TableNameVoices
}
